### ISSUE TITLE
Describe deployment

### ISSUE THREAD

**Issue by Lyla-Fischer** [fablabbcn/fablabs.io#350]
Hi, 

I'm looking into the possibility of using this repo for Ananse Group, and I was wondering what it would take to get a development version of the site set up. I don't see much that is helpful in the README, and I was wondering if it might be possible to add something to the documentation to make it easier to get a version of the site up and running. It looks like you use Docker and Travis, but do you deploy to AWS (if we wanted to copy your workflow rather than figure something out on our own). Any recommendations of tutorials to read/follow? Any help would be appreciated.

**Comment by johnrees** [comment]
@openp2pdesign I see you've assigned me to this, but I haven't looked at any of the code in a couple of years and I imagine a lot of things have changed since then (Docker etc). I'm going to remove myself for now because I don't think I'm much use here anymore, but if you need me back again just tag me and I'll try and help out. Thanks

**Comment by viktorsmari** [comment]
@Lyla-Fischer have you tried doing `docker-compose up` recently? We are running that on staging, and it gets an SSL cert via LetsEncrypt. We are working on improving this. Hopefully it will support Kubernetes in the next year.

**Comment by viktorsmari** [comment]
Closing because everything has been Dockerized and the README updated.
