### ISSUE TITLE
Logging / logout fails on test version

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/fablabs.io#437]
![giphy](https://user-images.githubusercontent.com/74249/45503350-e4631700-b786-11e8-92f8-33592c63eaf6.gif)

**Comment by fibasile** [comment]
The issue is related to cookies. If you are logged in to the production fablabs.io you have a cookie set on *.fablabs.io Then then production server adds a new cookie on test.fablabs.io.

So you need to logout the production fablabs.io to be able to enter the test (or delete the cookie)

![cookie](https://user-images.githubusercontent.com/32947/45957277-f3fb1f00-c014-11e8-90f1-a3f8b4db0a51.jpg)

**Comment by pral2a** [comment]
Thanks for the comment @fibasile I'll close the issue then
